[app_graph_org_accepts]
entities.edges = [["ORGANISATION", "COLLABORATION_1"],
                  ["ORGANISATION", "UNIT"],
                  ["UNIT", "COLLABORATION_2"]
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["COLLABORATION_1", "COLL_ADMIN_1"],
                     ["COLLABORATION_2", "COLL_ADMIN_2"],
                     ["APPLICATION", "APP_ADMIN"]
                     ]
entity_role.type = "BACKBONE"

actions.edges = [["ORG_ADMIN", "APPLICATION", "approves"],
                 ["APP_ADMIN", "COLLABORATION_2", "approves"],
                 ["APP_ADMIN", "COLLABORATION_1", "disapproves"]
                ]
actions.type = "ACTIONS"
explanation = "The organisation admin approves an application to be used by all collaborations. If the application admin also accpets that a collaboration uses the app, all members of the collaboration have access to the application."


[app_graph_org_denies]
entities.edges = [
                  ["ORGANISATION", "COLLABORATION"],
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["COLLABORATION", "COLL_ADMIN"],
                     ["APPLICATION", "APP_ADMIN"]
                     ]
entity_role.type = "BACKBONE"

actions.edges = [["ORG_ADMIN", "APPLICATION", "disapproves"],
                 ["APP_ADMIN", "COLLABORATION", "approves"],
                ]
actions.type = "ACTIONS"
explanation = "The organisation admin does not approve an application to be used by any collaboration. Even if the application admin accpets that a collaboration uses the app, none of the members of the collaboration have access to the application."


[all_nodes_graph]

entities.edges = [["ORGANISATION", "UNIT"],
                  ["ORGANISATION", "COLLABORATION_1"],
                  ["UNIT", "COLLABORATION_2"],
                  ["COLLABORATION_1", "APP_GROUP_1"],
                  ["COLLABORATION_1", "CO_GROUP_1"],
                  ["COLLABORATION_2", "APP_GROUP_2"],
                  ["COLLABORATION_2", "CO_GROUP_2"],
                  ["COLLABORATION_1", "APPLICATION_1"],
                  ["COLLABORATION_1", "APPLICATION_2"],
                  ["COLLABORATION_2", "APPLICATION_2"]
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["ORGANISATION", "ORG_MANAGER"],
                     ["UNIT", "U_MANAGER"],
                     ["COLLABORATION_1", "RESEARCHER_1"],
                     ["COLLABORATION_1", "RESEARCHER_2"],
                     ["COLLABORATION_2", "RESEARCHER_1"],
                     ["COLLABORATION_1", "COLL_ADMIN_1"],
                     ["COLLABORATION_1", "COLL_ADMIN_2"],
                     ["COLLABORATION_2", "COLL_ADMIN_1"]
                     ]
entity_role.type = "BACKBONE"

members.edges = [["RESEARCHER_1", "COLLABORATION_1", "member_of"],
                 ["RESEARCHER_1", "COLLABORATION_2",  "member_of"],
                 ["RESEARCHER_2", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_1", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_2", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_1", "COLLABORATION_2",  "member_of"],
                 ["RESEARCHER_1", "CO_GROUP_2"],
                 ["RESEARCHER_1", "APP_GROUP_2"],
                 ["RESEARCHER_2", "APP_GROUP_1"],
                 ["RESEARCHER_2", "CO_GROUP_1"]
                ]
members.type = "MEMBERS"

actions.edges = [["ORG_MANAGER", "COLLABORATION_1", "create"],
                 ["U_MANAGER", "COLLABORATION_2", "create"],
                 ["COLL_ADMIN_2", "RESEARCHER_1", "invite"],
                 ["COLL_ADMIN_1", "RESEARCHER_2", "invite"],
                 ["APPLICATION_2", "APP_GROUP_1", "create"],
                 ["APPLICATION_2", "APP_GROUP_2", "create"],
                 ["COLL_ADMIN_1", "CO_GROUP1", "create"],
                 ["COLL_ADMIN_1", "CO_GROUP2", "create"]
                ]
actions.type = "ACTIONS"

explanation = "A graph that shows all of the implemented node types and edges types."

[plain_graph]

entities.edges = [["ORGANISATION", "COLLABORATION"]]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["ORGANISATION", "ORG_MANAGER"],
                     ["COLLABORATION", "RESEARCHER_1"],
                     ["COLLABORATION", "RESEARCHER_2"],
                     ["COLLABORATION", "COLL_ADMIN"]
                    ]
entity_role.type = "BACKBONE"

members.edges = [["RESEARCHER_1", "COLLABORATION", "member_of"],
                 ["RESEARCHER_2", "COLLABORATION", "member_of"],
                 ["COLL_ADMIN", "COLLABORATION", "member_of"],
                ]
members.type = "MEMBERS"

actions.edges = [["ORG_MANAGER", "COLLABORATION", "create"],
                 ["COLL_ADMIN", "RESEARCHER_1", "invite"],
                 ["COLL_ADMIN", "RESEARCHER_2", "invite"]
                ]
actions.type = "ACTIONS"

explanation = "An easy understandable graph showing the most important concepts."
