[all_nodes_graph]

entities.edges = [["ORGANISATION", "UNIT"],
                  ["ORGANISATION", "COLLABORATION_1"],
                  ["UNIT", "COLLABORATION_2"],
                  ["COLLABORATION_1", "APP_GROUP_1"],
                  ["COLLABORATION_1", "CO_GROUP_1"],
                  ["COLLABORATION_2", "APP_GROUP_2"],
                  ["COLLABORATION_2", "CO_GROUP_2"],
                  ["COLLABORATION_1", "APPLICATION_1"],
                  ["COLLABORATION_1", "APPLICATION_2"],
                  ["COLLABORATION_2", "APPLICATION_2"]
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["ORGANISATION", "ORG_MANAGER"],
                     ["UNIT", "U_MANAGER"],
                     ["COLLABORATION_1", "RESEARCHER_1"],
                     ["COLLABORATION_1", "RESEARCHER_2"],
                     ["COLLABORATION_2", "RESEARCHER_1"],
                     ["COLLABORATION_1", "COLL_ADMIN_1"],
                     ["COLLABORATION_1", "COLL_ADMIN_2"],
                     ["COLLABORATION_2", "COLL_ADMIN_1"]
                     ]
entity_role.type = "BACKBONE"

members.edges = [["RESEARCHER_1", "COLLABORATION_1", "member_of"],
                 ["RESEARCHER_1", "COLLABORATION_2",  "member_of"],
                 ["RESEARCHER_2", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_1", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_2", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_1", "COLLABORATION_2",  "member_of"],
                 ["RESEARCHER_1", "CO_GROUP_2"],
                 ["RESEARCHER_1", "APP_GROUP_2"],
                 ["RESEARCHER_2", "APP_GROUP_1"],
                 ["RESEARCHER_2", "CO_GROUP_1"]
                ]
members.type = "MEMBERS"

actions.edges = [["ORG_MANAGER", "COLLABORATION_1", "create"],
                 ["U_MANAGER", "COLLABORATION_2", "create"],
                 ["COLL_ADMIN_2", "RESEARCHER_1", "invite"],
                 ["COLL_ADMIN_1", "RESEARCHER_2", "invite"],
                 ["APPLICATION_2", "APP_GROUP_1", "create"],
                 ["APPLICATION_2", "APP_GROUP_2", "create"],
                 ["COLL_ADMIN_1", "CO_GROUP1", "create"],
                 ["COLL_ADMIN_1", "CO_GROUP2", "create"]
                ]
actions.type = "ACTIONS"

explanation = "A graph that shows all of the implemented node types and edges types."

[plain_graph]

entities.edges = [["ORGANISATION", "COLLABORATION"]]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["ORGANISATION", "ORG_MANAGER"],
                     ["COLLABORATION", "RESEARCHER_1"],
                     ["COLLABORATION", "RESEARCHER_2"],
                     ["COLLABORATION", "COLL_ADMIN"]
                    ]
entity_role.type = "BACKBONE"

members.edges = [["RESEARCHER_1", "COLLABORATION", "member_of"],
                 ["RESEARCHER_2", "COLLABORATION", "member_of"],
                 ["COLL_ADMIN", "COLLABORATION", "member_of"],
                ]
members.type = "MEMBERS"

actions.edges = [["ORG_MANAGER", "COLLABORATION", "create"],
                 ["COLL_ADMIN", "RESEARCHER_1", "invite"],
                 ["COLL_ADMIN", "RESEARCHER_2", "invite"]
                ]
actions.type = "ACTIONS"

explanation = "A simpler graph that shows the most fundamental node types and edge types.."

[app_graph_org_accepts]
entities.edges = [["ORGANISATION", "COLLABORATION_1"],
                  ["ORGANISATION", "UNIT"],
                  ["UNIT", "COLLABORATION_2"]
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["COLLABORATION_1", "COLL_ADMIN_1"],
                     ["COLLABORATION_2", "COLL_ADMIN_2"],
                     ["APPLICATION", "APP_ADMIN"]
                     ]
entity_role.type = "BACKBONE"

actions.edges = [["ORG_ADMIN", "APPLICATION", "approves"],
                 ["APP_ADMIN", "COLLABORATION_2", "approves"],
                 ["APP_ADMIN", "COLLABORATION_1", "denies"]
                ]
actions.type = "ACTIONS"
explanation = """
This example graph shows the impact of actions when an Oragnisation enabled *Application connection request must be approved by the Organisation admin or manager* and an Application enabled the setting *I want to approve (connection) requests manually*.

Below we list the general workflow:

1. **Collaboration admin** creates an *Application Connection Request* to connect an Application to a collaboration.
2. The **Organisation admin / manager** reviews the *Application Connection Request* for an **Application** to a **Collaboration**.
4. The **Organisation admin/ manager** approves the *Application Connection Request*.
6. The **Application admin/manager** reviews the *Application Connection Request* for the given **Collaboration**.
7. The **Application admin/manager** approves (or disapproves).
8. The **Application** is only connected to a **Collaboration** with both, the Organisation and the Application Admins reviews and approvals.

In the graph above we show:

- Collaboration 1 and Collaboration 2 wish to make an application available for their members.
The Organisation has optionally decided to manually review all application connection requests.
- The two CO admins create each an *Application Connection Request* and the Organisation admin approves the submitted *Application Connection Requests*.
 Since the Organisation admin approved the requests, they continue to the Application admin/manager.
- The Application admin denies the request for Collaboration 1, and approves the request for Collaboration 2. All members of Collaboration 2 now have access to the Application.

"""

[app_graph_org_denies]
entities.edges = [
                  ["ORGANISATION", "COLLABORATION"],
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["COLLABORATION", "COLL_ADMIN"],
                     ["APPLICATION", "APP_ADMIN"]
                     ]
entity_role.type = "BACKBONE"

actions.edges = [["ORG_ADMIN", "APPLICATION", "denies"],
                ]
actions.type = "ACTIONS"
explanation = """
This example graph shows the impact of actions when an Oragnisation enabled *Application connection request must be approved by the Organisation admin or manager* and an Application enabled the setting *I want to approve (connection) requests manually*.

Below we list the general workflow:

1. **Collaboration admin** creates an *Application Connection Request* to connect an Application to a collaboration.
2. The **Organisation admin / manager** reviews the *Application Connection Request* for an **Application** to a **Collaboration**.
4. The **Organisation admin/ manager** approves the *Application Connection Request*.
6. The **Application admin/manager** reviews the *Application Connection Request* for the given **Collaboration**.
7. The **Application admin/manager** approves (or disapproves).
8. The **Application** is only connected to a **Collaboration** with both, the Organisation and the Application Admins reviews and approvals.

In the graph above we show:

- A Collaboration wishes to make an application available for its members.
- The Collaboration admin makes an Application Connection Request.
- The Organisation admin/manager denies the application connection request. Since the Organisation admin denied the request, the Application admin/manager does not receive the request.
- Members of the collaboration do not have access.
 
"""
