[node_types]
ORG_ADMIN.name = "admin"
ORG_ADMIN.level = 2
ORG_MANAGER.name = "role"
ORG_MANAGER.level = 2
U_MANAGER.name = "role"
U_MANAGER.level = 4
COLL_ADMIN.name = "admin"
COLL_ADMIN.level = 6
RESEARCHER.name = "user"
RESEARCHER.level = 8
CO_MEMBER.name = "user"
CO_MEMBER.level = 8
APP_ADMIN.name = "admin"
APP_ADMIN.level = 10

APPLICATION.name = "service"
APPLICATION.level = 9
COLLABORATION.name = "collaboration"
COLLABORATION.level = 5
ORGANISATION.name = "organisation"
ORGANISATION.level = 1
UNIT.name = "unit"
UNIT.level = 3
CO_GROUP.name = "group"
CO_GROUP.level = 7
APP_GROUP.name = "group"
APP_GROUP.level = 7

[node_colors]
role = "orange"
unit = "gray"
organisation = "gray"
collaboration = "gray"
group = "darkorange"
service = "blue"
user = "purple"
admin = "green"
entity = "gray"
default = "lightblue"

[edge_colors]
ACTIONS = "orange"
TRUST = "purple"
MEMBERS = "lightgray"
BACKBONE = "black"
REJECT = "red"
default = "lightblue"

[app_graph]
entities.edges = [["ORGANISATION_1", "COLLABORATION_1"],
                  ["ORGANISATION_1", "COLLABORATION_2"],
                  ["ORGANISATION_2", "COLLABORATION_3"],
                  ["COLLABORATION_2", "APPLICATION"],
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION_1", "ORG_ADMIN_1"],
                     ["ORGANISATION_2", "ORG_ADMIN_2"],
                     ["COLLABORATION_1", "COLL_ADMIN_1"],
                     ["COLLABORATION_2", "COLL_ADMIN_2"],
                     ["APPLICATION", "APP_ADMIN"]
                     ]
entity_role.type = "BACKBONE"

actions.edges = [["ORG_ADMIN_1", "APPLICATION", "approves"],
                 ["ORG_ADMIN_2", "APPLICATION", "disapproves"],
                 ["APP_ADMIN", "COLLABORATION_2", "approves"],
                 ["APP_ADMIN", "COLLABORATION_1", "disapproves"],
                 ["APP_ADMIN", "COLLABORATION_3", "approves"],
                ]
actions.type = "ACTIONS"


[all_nodes_graph]

entities.edges = [["ORGANISATION", "UNIT"],
                  ["ORGANISATION", "COLLABORATION_1"],
                  ["UNIT", "COLLABORATION_2"],
                  ["COLLABORATION_1", "APP_GROUP_1"],
                  ["COLLABORATION_1", "CO_GROUP_1"],
                  ["COLLABORATION_2", "APP_GROUP_2"],
                  ["COLLABORATION_2", "CO_GROUP_2"],
                  ["COLLABORATION_1", "APPLICATION_1"],
                  ["COLLABORATION_1", "APPLICATION_2"],
                  ["COLLABORATION_2", "APPLICATION_2"]
                  ]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["ORGANISATION", "ORG_MANAGER"],
                     ["UNIT", "U_MANAGER"],
                     ["COLLABORATION_1", "RESEARCHER_1"],
                     ["COLLABORATION_1", "RESEARCHER_2"],
                     ["COLLABORATION_2", "RESEARCHER_1"],
                     ["COLLABORATION_1", "COLL_ADMIN_1"],
                     ["COLLABORATION_1", "COLL_ADMIN_2"],
                     ["COLLABORATION_2", "COLL_ADMIN_1"]
                     ]
entity_role.type = "BACKBONE"

members.edges = [["RESEARCHER_1", "COLLABORATION_1", "member_of"],
                 ["RESEARCHER_1", "COLLABORATION_2",  "member_of"],
                 ["RESEARCHER_2", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_1", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_2", "COLLABORATION_1",  "member_of"],
                 ["COLL_ADMIN_1", "COLLABORATION_2",  "member_of"],
                 ["RESEARCHER_1", "CO_GROUP_2"],
                 ["RESEARCHER_1", "APP_GROUP_2"],
                 ["RESEARCHER_2", "APP_GROUP_1"],
                 ["RESEARCHER_2", "CO_GROUP_1"]
                ]
members.type = "MEMBERS"

actions.edges = [["ORG_MANAGER", "COLLABORATION_1", "create"],
                 ["U_MANAGER", "COLLABORATION_2", "create"],
                 ["COLL_ADMIN_2", "RESEARCHER_1", "invite"],
                 ["COLL_ADMIN_1", "RESEARCHER_2", "invite"],
                 ["APPLICATION_2", "APP_GROUP_1", "create"],
                 ["APPLICATION_2", "APP_GROUP_2", "create"],
                 ["COLL_ADMIN_1", "CO_GROUP1", "create"],
                 ["COLL_ADMIN_1", "CO_GROUP2", "create"]
                ]
actions.type = "ACTIONS"

[plain_graph]

entities.edges = [["ORGANISATION", "COLLABORATION"]]
entities.type = "BACKBONE"

entity_role.edges = [["ORGANISATION", "ORG_ADMIN"],
                     ["ORGANISATION", "ORG_MANAGER"],
                     ["COLLABORATION", "RESEARCHER_1"],
                     ["COLLABORATION", "RESEARCHER_2"],
                     ["COLLABORATION", "COLL_ADMIN"]
                    ]
entity_role.type = "BACKBONE"

members.edges = [["RESEARCHER_1", "COLLABORATION"],
                 ["RESEARCHER_2", "COLLABORATION"],
                 ["COLL_ADMIN", "COLLABORATION"],
                ]
members.type = "MEMBERS"

actions.edges = [["ORG_MANAGER", "COLLABORATION", "create"],
                 ["COLL_ADMIN", "RESEARCHER_1", "invite"],
                 ["COLL_ADMIN", "RESEARCHER_2", "invite"]
                ]
actions.type = "ACTIONS"
